name: flutter_pods
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter_riverpod: ^2.4.0
  meta: ^1.9.1
  pods:
    path: ../pods
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
