name: pocketbase_pods
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  pocketbase: ^0.14.1
  pods:
    path: ../pods
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  riverpod: ^2.3.10
  test: ^1.21.0
