name: drift_pods
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  drift: ^2.11.1
  riverpod: ^2.3.10
  pods:
    path: ../pods
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  drift_dev: ^2.11.1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
